server:
  port: ${DISCOVERY_SERVICE_PORT}

spring:
  application:
    name: ${DISCOVERY_SERVICE_NAME}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
        web:
          exposure:
            include: "*"

logging:
  level:
    org.springframework: info
