server:
  port: ${CONFIG_SERVICE_PORT}

spring:
  application:
    name: ${CONFIG_SERVICE_NAME}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs
        git:
          uri: https://github.com/${GIT_USER}/${GIT_CONFIG_REPOSITORY}
          clone-on-start: true
          default-label: master

logging:
  level:
    org.springframework: info
